...
24          run: chmod +x gradlew
25        - name: Build with Gradle
26          run: ./gradlew build
27        # --- NOUVELLE ÉTAPE POUR LES TESTS ---
28        - name: Run unit tests
29          run: ./gradlew :app:testDebugUnitTest